### ISSUE TITLE
Forced Bound Witness

### ISSUE THREAD

**Issue by maryannxy** [XYOracleNetwork/sdk-core-swift#12]
Determine and provide SDK changes needed for XYO Network app for iOS to bound witness on user input (in addition to extant predetermined intervals).

Dependent issues:
- https://github.com/XYOracleNetwork/app-xyo-ios/issues/17
- https://github.com/XYOracleNetwork/app-xyo-android/issues/314

**Comment by carterharrison** [comment]
This has been done and there is an example in both the iOS and android sample apps. @maryannxy

**Comment by maryannxy** [comment]
@carterharrison Rad!

**Comment by maryannxy** [comment]
@BobNies @oldsquarehead Can you gentlemen review and pass this, then ping me, when you have a chance?

Carter said it just needs to be implemented.
